name: latest-build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Runs cmake on the project to build
      - name: Build Metro
        run: |
          git submodule update --init --recursive
          mkdir build
          cd build
          cmake ..
          cmake --build .